package equivalence
import grammar._
import repair._
import parsing._
import generators._
import CFGrammar._
import EBNFGrammar._
import BNFConverter._

sealed abstract class EquivalenceResult
//object PossiblyEquivalent extends EquivalenceResult { 
//  override def toString = "Possibly correct!" 
//}
//object Aborted extends EquivalenceResult {
//  override def toString = "Operation aborted"
//}
case class NotEquivalentNotAcceptedBySolution(unparsableWord: List[Terminal]) extends EquivalenceResult {
  override def toString = "\"" + unparsableWord.mkString(" ") + "\"" + " is not accepted by the solution!"
}
case class NotEquivalentGeneratedBySolution(ungeneratableWord: List[Terminal]) extends EquivalenceResult {
  override def toString = "\"" + ungeneratableWord.mkString(" ") + "\"" + " is generated by the solution!"
}

abstract class EquivalenceChecker[T] {

  val refg: Grammar[T]
  val refParser : Parser   

  def isEquivalentTo(g2: Grammar[T]) : List[EquivalenceResult]   

  def isSuperset(g2: Grammar[T]) : List[Word] 
 
  //g2 is subset of refg
  def isSubset(g2: Grammar[T]) : List[Word]
  
  def getRefWords() : List[Word]
}